filebeat.prospectors:
  - type: log
    paths:
      - /log/*.log
      - /log/*/*.log
      - /log/*/*/*.log

# By setting ES as output we can send it the Index Template
setup.template.enabled: true
output.elasticsearch:
  hosts: ["192.168.5.15:5044"]

# After having sent the Index Template, send to Kibana the Dashboards
setup.dashboards.enabled: true
setup.kibana:
  host: "192.168.5.5:5601"
